nginx:
  config: |-
    user nginx;
    worker_processes 1;

    error_log stderr info;
    pid /var/run/nginx.pid;

    events {
      worker_connections 1024;
    }

    http {
      upstream service {
        server web-service.bolagetio.svc.cluster.local:3000;
      }

      server {
        server_name "~^.*$";

        location = /ready {
          return 200;
        }

        location / {
          proxy_pass http://service;
        }
      }
    }
