ingress:
  enabled: true

certificate:
  enabled: true

elasticsearch:
  replicas: 3
  numberOfMasters: 2
  storageClassName: ssd

nginx:
  replicas: 3

  image:
    repository: eu.gcr.io/brynn-145714/bolagetio/nginx-deployment
    tag: latest
    pullPolicy: IfNotPresent

  service:
    type: NodePort
    port: 80

web:
  replicas: 3

  image:
    repository: eu.gcr.io/brynn-145714/bolagetio/web-deployment
    tag: latest
    pullPolicy: IfNotPresent

  job:
    schedule: 00 03 * * *

  configmap:
    nodeEnv: production
    elasticIndexReplicas: 2
    elasticIndexShards: 3