ingress:
  enabled: true

certificate:
  enabled: true

elastic:
  image: eu.gcr.io/brynn-145714/bolagetio/elasticsearch
  imageTag: 7.1.1
  esJavaOpts: "-Xms512m -Xmx512m"
  terminationGracePeriod: 20

  resources:
    requests:
      cpu: "100m"
      memory: "1Gi"
    limits:
      cpu: "1000m"
      memory: "1Gi"

  volumeClaimTemplate:
    storageClassName: "ssd"
    accessModes: [ "ReadWriteOnce" ]
    resources:
      requests:
        storage: 10Gi

elasticsearch:
  replicas: 3
  numberOfMasters: 2
  storageClassName: ssd

nginx:
  replicas: 3

  image:
    repository: eu.gcr.io/brynn-145714/bolagetio/nginx-deployment
    tag: latest
    pullPolicy: IfNotPresent

  service:
    type: NodePort
    port: 80

web:
  replicas: 3

  image:
    repository: eu.gcr.io/brynn-145714/bolagetio/web-deployment
    tag: latest
    pullPolicy: IfNotPresent

  job:
    schedule: 00 03 * * *

  configmap:
    nodeEnv: production
    elasticIndexReplicas: 2
    elasticIndexShards: 3