ingress:
  enabled: true

certificate:
  enabled: true

elastic:
  replicas: 5
  maxUnavailable: 2
  image: eu.gcr.io/brynn-145714/bolagetio/elasticsearch-oss
  imageTag: 7.2.0
  esJavaOpts: "-Xms512m -Xmx512m"
  terminationGracePeriod: 20

  resources:
    requests:
      cpu: "100m"
      memory: "1Gi"
    limits:
      cpu: "1000m"
      memory: "1Gi"

  volumeClaimTemplate:
    storageClassName: "ssd"
    accessModes: [ "ReadWriteOnce" ]
    resources:
      requests:
        storage: 10Gi

nginx:
  replicas: 8

  image:
    repository: eu.gcr.io/brynn-145714/bolagetio/nginx-deployment
    tag: latest
    pullPolicy: IfNotPresent

  service:
    type: NodePort
    port: 80

web:
  replicas: 8

  image:
    repository: eu.gcr.io/brynn-145714/bolagetio/web-deployment
    tag: latest
    pullPolicy: IfNotPresent

  job:
    schedule: 0 * * * * # @hourly

  configmap:
    nodeEnv: production
    elasticIndexReplicas: 4
    elasticIndexShards: 1