ingress:
  enabled: false

certificate:
  enabled: false

elasticsearch:
  replicas: 1
  numberOfMasters: 1

nginx:
  replicas: 1

  image:
    repository: eu.gcr.io/brynn-145714/bolagetio/nginx-deployment
#    repository: docker.for.mac.localhost:5000/bolagetio/nginx-deployment
    tag: latest
    pullPolicy: Always

  service:
    type: ClusterIP
    port: 80

web:
  replicas: 1

  image:
    repository: eu.gcr.io/brynn-145714/bolagetio/web-deployment
#    repository: docker.for.mac.localhost:5000/bolagetio/web-deployment
    tag: latest
    pullPolicy: Always

  job:
    schedule: 00 03 * * *

  configmap:
    nodeEnv: development
    elasticIndexReplicas: 0
    elasticIndexShards: 1

  development: true

#  # Mount project files in container to allow sync and changes to
#  # take affect without rebuilding docker image while developing
#  volumeMounts:
#    mountPath: /home/node/web/src
#  volumes:
#    hostPath:
#      path: PATH/TO/THIS/REPO/bolaget.io/services/web/src
