ingress:
  enabled: false

certificate:
  enabled: false

elasticsearch:
  replicas: 1
  numberOfMasters: 1

nginx:
  replicas: 1

  image:
    repository: eu.gcr.io/brynn-145714/bolagetio/nginx-deployment
    tag: local
    pullPolicy: Never

  service:
    type: ClusterIP
    port: 80

web:
  replicas: 1

  image:
    repository: eu.gcr.io/brynn-145714/bolagetio/web-deployment
    tag: local
    pullPolicy: Never

  job:
    schedule: 00 03 * * *

  configmap:
    nodeEnv: development
    elasticIndexReplicas: 0
    elasticIndexShards: 1

  development: true
