ingress:
  enabled: true

certificate:
  enabled: true

vault:
  image: vault:1.2.3
  uri: https://vault.sthlm.io

consul:
  image: hashicorp/consul-template:0.22.0-alpine

elastic:
  replicas: 4
  maxUnavailable: 2
  image: eu.gcr.io/brynn-145714/bolagetio/elasticsearch-oss
  imageTag: 7.4.0
  esJavaOpts: "-Xms512m -Xmx512m"
  terminationGracePeriod: 20

  resources:
    requests:
      cpu: "100m"
      memory: "1Gi"
    limits:
      cpu: "1000m"
      memory: "1Gi"

  volumeClaimTemplate:
    storageClassName: "ssd"
    accessModes: [ "ReadWriteOnce" ]
    resources:
      requests:
        storage: 10Gi

nginx:
  replicas: 6

  image:
    repository: eu.gcr.io/brynn-145714/bolagetio/nginx-deployment
    tag: latest
    pullPolicy: IfNotPresent

  service:
    type: NodePort
    port: 80

web:
  replicas: 6

  image:
    repository: eu.gcr.io/brynn-145714/bolagetio/web-deployment
    tag: latest
    pullPolicy: IfNotPresent

  job:
    schedule: 0 * * * * # @hourly

  configmap:
    nodeEnv: production
    elasticIndexReplicas: 3
    elasticIndexShards: 1