ingress:
  enabled: true

certificate:
  enabled: true

vault:
  image: vault:1.2.3
  uri: https://vault.sthlm.io

consul:
  image: hashicorp/consul-template:0.22.0-alpine

elastic:
  replicas: 4
  maxUnavailable: 2
  image: eu.gcr.io/brynn-145714/bolagetio/elasticsearch-oss
  imageTag: 7.4.0
  esJavaOpts: "-Xms512m -Xmx512m"
  terminationGracePeriod: 20

  resources:
    requests:
      cpu: "100m"
      memory: "1Gi"
    limits:
      cpu: "1000m"
      memory: "1Gi"

  volumeClaimTemplate:
    storageClassName: "ssd"
    accessModes: [ "ReadWriteOnce" ]
    resources:
      requests:
        storage: 10Gi

nginx:
  replicas: 6

  image:
    repository: nginx
    tag: 1.17.4-alpine
    pullPolicy: IfNotPresent

  service:
    type: NodePort
    port: 80

  config: |-
    user nginx;
    worker_processes 1;

    error_log stderr info;
    pid /var/run/nginx.pid;

    events {
      worker_connections 1024;
    }

    http {
      server_tokens     off;

      upstream service {
        server web-service.bolagetio.svc.cluster.local:3000;
      }

      server {
        server_name www.bolaget.io;

        # First we redirect everything to https
        if ($http_x_forwarded_proto = "http") {
          return 301 https://$host$request_uri;
        }

        # Here, we are working with https content
        return 301 https://bolaget.io$request_uri;
      }

      server {
        server_name bolaget.io;

        # First we redirect everything to https
        if ($http_x_forwarded_proto = "http") {
          return 301 https://$host$request_uri;
        }

        # Here, we are working with https content
        add_header Access-Control-Allow-Origin *;
        add_header Cache-Control "public,max-age=60,must-revalidate";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        location / {
          proxy_pass http://service;
        }
      }

      server {
        server_name "~^.*$";

        location = /ready {
          return 200;
        }
      }
    }

web:
  replicas: 6

  image:
    repository: eu.gcr.io/brynn-145714/bolagetio/web-deployment
    tag: latest
    pullPolicy: IfNotPresent

  job:
    schedule: "@hourly"

  configmap:
    nodeEnv: production
    elasticIndexReplicas: 3
    elasticIndexShards: 1