#!/bin/bash

set -e

eval $(docker-machine env manager1)

docker service create \
  --with-registry-auth \
  --name bolagetio_elasticsearch \
  --replicas 1 \
  --limit-memory 512m \
  -e ES_HEAP_SIZE=256m \
  --restart-condition any \
  --restart-max-attempts 10 \
  --network bolagetio \
  fredriklack/bolaget.io:elasticsearch

docker service create \
  --with-registry-auth \
  --name bolagetio_web \
  --replicas 1 \
  -e NODE_ENV=production \
  -e ELASTIC_INDEX=bolaget_prod \
  -e ELASTIC_LOG=error \
  --network bolagetio \
  -w /web \
  --restart-condition any \
  --restart-max-attempts 10 \
  fredriklack/bolaget.io:node \
  npm run production

docker service create \
  --with-registry-auth \
  --name bolagetio_worker \
  --replicas 1 \
  -e NODE_ENV=production \
  -e ELASTIC_INDEX=bolaget_prod \
  -e ELASTIC_LOG=error \
  --network bolagetio \
  --restart-condition none \
  -w /web \
  fredriklack/bolaget.io:node \
  npm run worker
