sudo: required
services:
  - docker
install:
  - ./build
script:
  - docker run -d -p 9200:9200/tcp --name bolagetio_elasticsearch -e ES_HEAP_SIZE=256m bolagetio_elasticsearch
  - sleep 10
  - docker run -w /web --name bolagetio_test --link bolagetio_elasticsearch bolagetio_web npm test
