sudo: required
language: node_js
node_js:
  - "6.5.0"
services:
  - docker
install:
  - ./build
script:
  - docker run -d -p 9200:9200/tcp --name bolagetio_elasticsearch -e ES_HEAP_SIZE=256m bolagetio_elasticsearch
  - docker run -i -d -w /web --name bolagetio_test --link bolagetio_elasticsearch bolagetio_web npm test
