sudo: required
language: node_js
services:
  - docker
install:
  - docker build --force-rm -t bolagetio_elasticsearch -f Dockerfile.es .
  - docker run -d -p 9200:9200/tcp --name bolagetio_elasticsearch -e ES_HEAP_SIZE=256m bolagetio_elasticsearch
