sudo: required
services:
  - docker

cache:
  directories:
    - "$HOME/google-cloud-sdk/"
    - services/web/node_modules

env:
  global:
    - PROJECT_NAME=brynn-145714
    - CLUSTER_NAME=production
    - CLOUDSDK_COMPUTE_ZONE=europe-north1-a
    - DOCKER_IMAGE_NAME=bolagetio
    - K8S_NAMESPACE=bolagetio
    - K8S_DEPLOYMENT_NAME_WEB=web-deployment
    - COMMIT=${TRAVIS_COMMIT::7}
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
    - ELASTICSEARCH_VERSION=7.5.1

script:
  - ./scripts/travis-gcloud.sh
  - ./scripts/travis-build.sh
  - ./scripts/travis-test.sh

deploy:
  - provider: script
    script: ./scripts/travis-deploy.sh
    skip_cleanup: true
    on:
      branch: master

notifications:
  email: false
  slack:
    secure: kfR9gx9UVvswI2x6WRyyX2KZH2ijT/+F6n/RPouBzPmqDCnz9TBcT908CVRXlN1aZOO1AXTUllaZKjmcuUuJ8Vv7DmEEQr/eSq+c5f0wEnUJaKftSu8CJQ25o56QX4TedQA9hLfBboR6q+2RvVOX32UflN7jDzf2wU/bV1t/dd54O9Brf23/nOnfX5rIMjWYcNrJ16Fe/k+EwMRYlhR4vNmEpn+2yxCMWGIseIsZ1kfQIicTYWmqkw0WjhSO5qaDdH2jML8L2rzpqTjjI+YWqsZ8t8xk0pHz9guDubsZ/L+fJcqqB7mA+vEVACTZnq1cXP/O9Dx78ob3Pkgcquixqq4n8kPNxG/m6SdNw9ZO/jmWbQBhejQofE06a+9rQ+Xojea97bjpz/XZN5815MhnGpOevpP4byigmc4R0Ml+SdnBYGF/JVjQCGsFGLrOdL9255M9DwJ0yPdPWByNH28R+pWlRZIY6ktz6pR6Tgjij4+0olWAGXMY8P7B2AhR2M1WPf04sPJuAyJEXFegvODHEf1OOyNqUnL6GtPneJwVT90JKh56LP65R7q1JmwEYbOKV/SIkLNzUg+sVjRm6o8bQUe2s4U4ExHTQzVYq1NX+YwpC0DJnU8nWNlTsbgm/hO9b7QTJ3W2J+FFXGUf2Cd62OpFTK+uSQAkM91GGjXZRNs=
