sudo: required
services:
- docker
cache:
  directories:
  - "$HOME/google-cloud-sdk/"
  - node_modules
env:
  global:
  - DOCKER_COMPOSE_VERSION=1.17.1
  - PROJECT_NAME=brynn-145714
  - CLUSTER_NAME=d6658a9defae77f1757cb09d67b818757cd24486
  - CLOUDSDK_COMPUTE_ZONE=europe-west3-c
  - DOCKER_IMAGE_NAME=bolagetio
  - K8S_NAMESPACE=bolagetio
  - K8S_DEPLOYMENT_NAME_WEB=web-deployment
  - K8S_DEPLOYMENT_NAME_NGINX=nginx-deployment
  - COMMIT=${TRAVIS_COMMIT::7}
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
install:
- docker-compose build
script:
- docker-compose up -d elastic
- sleep 20
- docker-compose run --rm web npm test
deploy:
- provider: script
  script: "./devops/script/deploy.sh"
  skip_cleanup: true
  on:
    branch: master
- provider: script
  script: "./devops/script/deploy.sh"
  skip_cleanup: true
  on:
    branch: feature/elasticsearch-6.1.2-and-refactoring
notifications:
  email: false
  slack:
    secure: kfR9gx9UVvswI2x6WRyyX2KZH2ijT/+F6n/RPouBzPmqDCnz9TBcT908CVRXlN1aZOO1AXTUllaZKjmcuUuJ8Vv7DmEEQr/eSq+c5f0wEnUJaKftSu8CJQ25o56QX4TedQA9hLfBboR6q+2RvVOX32UflN7jDzf2wU/bV1t/dd54O9Brf23/nOnfX5rIMjWYcNrJ16Fe/k+EwMRYlhR4vNmEpn+2yxCMWGIseIsZ1kfQIicTYWmqkw0WjhSO5qaDdH2jML8L2rzpqTjjI+YWqsZ8t8xk0pHz9guDubsZ/L+fJcqqB7mA+vEVACTZnq1cXP/O9Dx78ob3Pkgcquixqq4n8kPNxG/m6SdNw9ZO/jmWbQBhejQofE06a+9rQ+Xojea97bjpz/XZN5815MhnGpOevpP4byigmc4R0Ml+SdnBYGF/JVjQCGsFGLrOdL9255M9DwJ0yPdPWByNH28R+pWlRZIY6ktz6pR6Tgjij4+0olWAGXMY8P7B2AhR2M1WPf04sPJuAyJEXFegvODHEf1OOyNqUnL6GtPneJwVT90JKh56LP65R7q1JmwEYbOKV/SIkLNzUg+sVjRm6o8bQUe2s4U4ExHTQzVYq1NX+YwpC0DJnU8nWNlTsbgm/hO9b7QTJ3W2J+FFXGUf2Cd62OpFTK+uSQAkM91GGjXZRNs=
