sudo: required
language: node_js
node_js:
  - "6.5.0"
services:
  - docker
install:
  - ./build
before_script:
  - sleep 10
  - npm install
script:
  - docker run -i -d -w /web --name bolagetio_test --link bolagetio_elasticsearch bolagetio_web npm test
