#!/bin/bash

set -e

docker run -d \
  -p 9200:9200/tcp \
  --name bolagetio_elasticsearch \
  -e ES_HEAP_SIZE=256m \
  bolagetio_elasticsearch

docker run \
  -v $(pwd):/web \
  -w /web \
  --name bolagetio_web \
  --link bolagetio_elasticsearch \
  -e NODE_ENV=development \
  -e ELASTIC_INDEX=bolaget_dev \
  -e ELASTIC_LOG=trace \
  -p 3000:3000/tcp \
  bolagetio_web \
  npm run dev
