version: '2'
services:
  travis:
    extends:
      file: docker-compose.base.yml
      service: base
    environment:
      - COVERALLS_REPO_TOKEN=${COVERALLS_REPO_TOKEN}
      - TRAVIS=${TRAVIS}
      - TRAVIS_BRANCH=${TRAVIS_BRANCH}
      - TRAVIS_JOB_ID=${TRAVIS_JOB_ID}
      - ELASTIC_INDEX=bolaget_test
    command: npm run test:travis
    depends_on:
      - elastic
  test:
    extends:
      file: docker-compose.base.yml
      service: base
    environment:
      - ELASTIC_INDEX=bolaget_test
    command: npm test
    depends_on:
      - elastic
  worker:
    extends:
      file: docker-compose.base.yml
      service: base
    command: npm run dev:worker
    depends_on:
      - elastic
  web:
    extends:
      file: docker-compose.base.yml
      service: base
    command: npm run dev
    ports:
      - "3000:3000"
      - "3001:3001"
    depends_on:
      - elastic
  elastic:
    build:
      context: .
      dockerfile: Dockerfile.elasticsearch
    environment:
      - ES_HEAP_SIZE=256m
    ports:
      - "9200:9200"
