version: '2'
services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.web
    command: npm run dev:test
    volumes:
      - .:/web
      - /web/node_modules
    depends_on:
      - elastic
  worker:
    build:
      context: .
      dockerfile: Dockerfile.web
    command: npm run dev:worker
    volumes:
      - .:/web
      - /web/node_modules
    depends_on:
      - elastic
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - .:/web
      - /web/node_modules
    depends_on:
      - elastic
  elastic:
    build:
      context: .
      dockerfile: Dockerfile.elasticsearch
    environment:
      - ES_HEAP_SIZE=256m
    ports:
      - "9200:9200"
