version: "3"
volumes:
  node_modules:
services:
  web:
    build:
      context: services/web
    environment:
      - NODE_ENV=development
      - ELASTIC_HOST=http://elastic:9200
      - ELASTIC_INDEX_SHARDS=1
      - ELASTIC_INDEX_REPLICAS=0
      - ELASTIC_REQUEST_TIMEOUT=10000
      - PORT=3000
      - SYSTEM_PORT=3001
    volumes:
      - ./services/web:/home/node/web
      - node_modules:/home/node/web/node_modules
    command: npm run dev
    ports:
      - "3000:3000"
      - "3001:3001"
    depends_on:
      - elastic
  elastic:
    build:
      context: services/elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
