version: '2'
services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.web
    command: npm test
    container_name: bolagetio_test
    volumes:
      - .:/web
      - /web/node_modules
    depends_on:
      - elastic
    links:
      - elastic
  worker:
    build:
      context: .
      dockerfile: Dockerfile.web
    command: npm run dev:worker
    container_name: bolagetio_worker
    volumes:
      - .:/web
      - /web/node_modules
    depends_on:
      - elastic
    links:
      - elastic
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    command: npm run dev
    container_name: bolagetio_web
    ports:
      - "3000:3000"
    volumes:
      - .:/web
      - /web/node_modules
    depends_on:
      - elastic
    links:
      - elastic
  elastic:
    build:
      context: .
      dockerfile: Dockerfile.elasticsearch
    container_name: bolagetio_elasticsearch
    environment:
      - ES_HEAP_SIZE=256m
    ports:
      - "9200:9200"
