#!/bin/bash

set -e

WEB=bolagetio_web
ELASTIC=bolagetio_elasticsearch
WORKER=bolagetio_worker

build () {
  docker build --force-rm -t $WEB -f Dockerfile.web .
  docker build --force-rm -t $ELASTIC -f Dockerfile.elasticsearch .
}

worker () {
  ! docker rm --force $WORKER
  docker run -t -i --rm \
    -w /web \
    --name $WORKER \
    --link $ELASTIC \
    --env-file .env \
    $WEB \
    npm run worker
}

web () {
  ! docker rm --force $WEB
  docker run -d \
    -w /web \
    --name $WEB \
    --link $ELASTIC \
    --env-file .env \
    --restart always \
    $WEB \
    npm run production
}

elastic () {
  ! docker rm --force $ELASTIC
  docker run -d \
    --name $ELASTIC \
    --memory 512m \
    -e ES_HEAP_SIZE=256m \
    --restart always \
    $ELASTIC
}

test () {
  docker run -t -i --rm \
    -w /web \
    --name bolagetio_test \
    --link $ELASTIC \
    $WEB \
    npm test
}

remove () {
  ! docker rm --force $WEB
  ! docker rm --force $WORKER
  ! docker rm --force $ELASTIC
}

release () {
  git checkout master
  git pull
  build
  web
}

$1
