nginx:
  image: fredriklack/brynn:bolagetio_nginx
  expose:
    - "80"
  labels:
    io.rancher.container.pull_image: always
worker:
  image: fredriklack/brynn:bolagetio_web
  command: npm run worker
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.start_once: true,
    com.socialengine.rancher-cron.schedule: @midnight
web:
  image: fredriklack/brynn:bolagetio_web
  restart: always
  expose:
    - "3000"
  environment:
    NODE_ENV: production
  labels:
    io.rancher.container.pull_image: always
elastic:
  image: fredriklack/brynn:bolagetio_elasticsearch
  restart: always
  mem_limit: 1g
  expose:
    - "9200"
  environment:
    ES_HEAP_SIZE: 512m
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: persistent_host=true
  volumes:
    - /var/lib/bolagetio/esdata:/usr/share/elasticsearch/data
