version: '2'
services:
  worker:
    image: fredriklack/brynn:bolagetio_web
    command: npm run worker
    depends_on:
      - elastic
  nginx:
    image: fredriklack/brynn:bolagetio_nginx
    restart: always
    depends_on:
      - web
  web:
    image: fredriklack/brynn:bolagetio_web
    restart: always
    environment:
      NODE_ENV: production
    depends_on:
      - elastic
  elastic:
    image: fredriklack/brynn:bolagetio_elasticsearch
    restart: always
    environment:
      ES_HEAP_SIZE: 512m
    volumes:
      - /usr/share/bolagetio/elasticsearch/data:/usr/share/elasticsearch/data
