#!/bin/bash

set -e

# docker service create \
#   --with-registry-auth \
#   --name bolagetio_elasticsearch \
#   --replicas 1 \
#   --limit-memory 512m \
#   -e ES_HEAP_SIZE=256m \
#   --restart-condition any \
#   --restart-max-attempts 10 \
#   --network cloud \
#   fredriklack/bolaget.io:elasticsearch
#
# docker service create \
#   --with-registry-auth \
#   --name bolagetio_web \
#   --replicas 1 \
#   -e NODE_ENV=production \
#   -e ELASTIC_INDEX=bolaget_prod \
#   -e ELASTIC_LOG=error \
#   -w /web \
#   --restart-condition any \
#   --restart-max-attempts 10 \
#   --network cloud \
#   fredriklack/bolaget.io:node \
#   npm run production
#
# docker service create \
#   --name bolagetio_worker \
#   -e NODE_ENV=production \
#   -e ELASTIC_INDEX=bolaget_prod \
#   -e ELASTIC_LOG=error \
#   --network cloud \
#   --restart-condition none \
#   -w /web \
#   fredriklack/bolaget.io:node \
#   npm run worker

docker run -d \
  --name bolagetio_elasticsearch \
  --memory 512m \
  -e ES_HEAP_SIZE=256m \
  --restart always \
  bolagetio_elasticsearch

docker run -d \
  -w /web \
  --name bolagetio_web \
  --link bolagetio_elasticsearch \
  -e NODE_ENV=production \
  -e ELASTIC_INDEX=bolaget_prod \
  -e ELASTIC_LOG=error \
  --restart always \
  bolagetio_web \
  npm run production
