worker:
  image: fredriklack/brynn:web
  command: npm run worker
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.start_once: true
web:
  image: fredriklack/brynn:web
  restart: always
  expose:
    - "3000"
  environment:
    NODE_ENV: production
  labels:
    io.rancher.container.pull_image: always
elastic:
  image: fredriklack/brynn:elasticsearch
  restart: always
  mem_limit: 512m
  expose:
    - "9200"
  environment:
    ES_HEAP_SIZE: 256m
  labels:
    io.rancher.container.pull_image: always
  volumes:
    - /bolagetio/elasticsearch/data:/usr/share/elasticsearch/data
  volume_driver: nfs
