version: '2'
services:
  worker:
    scale: 1
    labels:
      io.rancher.container.start_once: 'true'
      com.socialengine.rancher-cron.schedule: '@midnight'
  nginx:
    scale: 1
    log_driver: "journald"
    health_check:
      port: 30443
      interval: 2000
      initializing_timeout: 60000
      unhealthy_threshold: 3
      strategy: recreate
      healthy_threshold: 2
      response_timeout: 2000
    upgrade_strategy:
      start_first: true
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
  web:
    scale: 1
    log_driver: "journald"
    upgrade_strategy:
      start_first: true
    health_check:
      port: 3000
      interval: 2000
      initializing_timeout: 60000
      unhealthy_threshold: 3
      strategy: recreate
      healthy_threshold: 2
      response_timeout: 2000
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
  elastic:
    mem_limit: 1000000000
    health_check:
      port: 9200
      interval: 2000
      initializing_timeout: 60000
      unhealthy_threshold: 3
      strategy: recreate
      healthy_threshold: 2
      response_timeout: 2000
    labels:
      io.rancher.scheduler.affinity:host_label: persistent=true
    volumes:
      - /usr/share/bolagetio/elasticsearch/data:/usr/share/elasticsearch/data
