apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
  namespace: bolagetio
  labels:
    app: bolagetio
spec:
  ports:
  - name: http
    port: 9200
    protocol: TCP
  - name: transport
    port: 9300
    protocol: TCP
  selector:
    service: elasticsearch-statefulset
