apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  ports:
  - port: {{ .Values.nginx.service.port }}
    protocol: TCP
  type: {{ .Values.nginx.service.type | quote }}
  selector:
    app: nginx-deployment
