apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: bolagetio
spec:
  revisionHistoryLimit: 2
  replicas: {{ .Values.nginx.replicas }}
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: nginx-deployment
  template:
    metadata:
      labels:
        app: bolagetio
        service: nginx-deployment
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: service
                  operator: In
                  values:
                  - nginx-deployment
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 60
      containers:
      - name: nginx
        image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}"
        lifecycle:
          preStop:
            exec:
              command: ["sleep", "30"]
        imagePullPolicy: Always
        resources:
          limits:
            memory: "100Mi"
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /ready
            port: 80
          periodSeconds: 1
          successThreshold: 1
          failureThreshold: 1
        livenessProbe:
          httpGet:
            path: /ready
            port: 80
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 1
