apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
  labels:
    chart: {{ template "chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  nginx.conf: {{ toYaml .Values.nginx.config | indent 2 }}