apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: job
  annotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
spec:
  schedule: {{ .Values.web.job.schedule | quote }}
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            checksum/config: {{ include (print $.Template.BasePath "/web-configmap.yaml") . | sha256sum }}
          labels:
            app: job
        spec:
          volumes:
            - name: vault-token
              emptyDir:
                medium: Memory
            - name: config
              configMap:
                name: vault-agent-config
                items:
                  - key: vault-agent-config.hcl
                    path: vault-agent-config.hcl
                  - key: consul-template-config.hcl
                    path: consul-template-config.hcl
            - name: secrets
              emptyDir: {}
          initContainers:
          - name: vault-agent-auth
            image: {{ .Values.vault.image }}
            volumeMounts:
              - name: config
                mountPath: /etc/vault
              - name: vault-token
                mountPath: /home/vault
            env:
              - name: VAULT_ADDR
                value: {{ .Values.vault.uri }}
            args: ["agent", "-config=/etc/vault/vault-agent-config.hcl"]
          - name: consul-template
            image: {{ .Values.consul.image }}
            imagePullPolicy: Always
            volumeMounts:
              - name: vault-token
                mountPath: /home/vault
              - name: config
                mountPath: /etc/consul-template
              - name: secrets
                mountPath: /etc/secrets
            env:
              - name: HOME
                value: /home/vault
              - name: VAULT_ADDR
                value: {{ .Values.vault.uri }}
            args: ["-config=/etc/consul-template/consul-template-config.hcl", "-once"]
          containers:
          - name: job
            image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
            imagePullPolicy: {{ .Values.web.image.pullPolicy | quote }}
            volumeMounts:
              - name: secrets
                mountPath: /home/node/web/.env
                subPath: .env
                readOnly: true
            envFrom:
            - configMapRef:
                name: web-config
            command: ["node", ".build/worker.js"]
          restartPolicy: OnFailure
