apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  revisionHistoryLimit: 2
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 25%
    type: RollingUpdate
  selector:
    matchLabels:
      app: web-deployment
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/web-configmap.yaml") . | sha256sum }}
      labels:
        app: web-deployment
    spec:
      volumes:
        - name: vault-token
          emptyDir:
            medium: Memory
        - name: config
          configMap:
            name: vault-agent-config
            items:
              - key: vault-agent-config.hcl
                path: vault-agent-config.hcl
              - key: consul-template-config.hcl
                path: consul-template-config.hcl
        - name: secrets
          emptyDir: {}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                    - web-deployment
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 20
      initContainers:
      - name: vault-agent-auth
        image: vault
        volumeMounts:
          - name: config
            mountPath: /etc/vault
          - name: vault-token
            mountPath: /home/vault
        env:
          - name: VAULT_ADDR
            value: https://vault.sthlm.io
        args:
          [
            "agent",
            "-config=/etc/vault/vault-agent-config.hcl",
            #"-log-level=debug",
          ]
      containers:
      - name: consul-template
        image: hashicorp/consul-template:alpine
        imagePullPolicy: Always
        volumeMounts:
          - name: vault-token
            mountPath: /home/vault
          - name: config
            mountPath: /etc/consul-template
          - name: secrets
            mountPath: /etc/secrets
        env:
          - name: HOME
            value: /home/vault
          - name: VAULT_ADDR
            value: https://vault.sthlm.io
        args:
          [
            "-config=/etc/consul-template/consul-template-config.hcl",
            #"-log-level=debug",
          ]
      - name: web
        image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
        command: ["node", "--max-old-space-size=128", ".build/web.js"]
        imagePullPolicy: {{ .Values.web.image.pullPolicy | quote }}
        volumeMounts:
          - name: secrets
            mountPath: /home/node/web/.env
            subPath: .env
            readOnly: true
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 200Mi
        envFrom:
        - configMapRef:
            name: web-config
        ports:
        - containerPort: 3000
        - containerPort: 3001
        readinessProbe:
          httpGet:
            path: /ready
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 1
          successThreshold: 1
          failureThreshold: 1
        livenessProbe:
          httpGet:
            path: /ready
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 1
        lifecycle:
          preStop:
            httpGet:
              path: /prestop
              port: 3001
