apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: job
  namespace: bolagetio
spec:
  schedule: {{ .Values.web.job.schedule | quote }}
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            checksum/config: {{ include (print $.Template.BasePath "/web-configmap.yaml") . | sha256sum }}
          labels:
            app: bolagetio
            service: job
        spec:
          containers:
          - name: job
            image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
            imagePullPolicy: {{ .Values.web.image.pullPolicy | quote }}
            envFrom:
            - configMapRef:
                name: web-config
            command: ["node", ".build/worker.js"]
          restartPolicy: OnFailure
