kind: ConfigMap
apiVersion: v1
metadata:
  name: web-config
data:
  PORT: "3000"
  SYSTEM_PORT: "3001"
  ELASTIC_REQUEST_TIMEOUT: "10000"
  ELASTIC_HOST: "elasticsearch-master.bolagetio.svc.cluster.local:9200"
  NODE_ENV: {{ .Values.web.configmap.nodeEnv | quote }}
  ELASTIC_INDEX_REPLICAS: {{ .Values.web.configmap.elasticIndexReplicas | quote }}
  ELASTIC_INDEX_SHARDS: {{ .Values.web.configmap.elasticIndexShards | quote }}
