apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: bolagetio
spec:
  revisionHistoryLimit: 2
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: elasticsearch-storage
      containers:
      - name: elasticsearch
        volumeMounts:
        - name: storage
          mountPath: /usr/share/elasticsearch/data
        image: eu.gcr.io/brynn-145714/bolagetio/elasticsearch:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "512Mi"
          limits:
            memory: "1Gi"
        env:
        - name: ES_HEAP_SIZE
          value: "512m"
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
