apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-storage
  namespace: bolagetio
spec:
  storageClassName: ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
