apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
  namespace: bolagetio
spec:
  revisionHistoryLimit: 2
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      terminationGracePeriodSeconds: 60
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
      containers:
      - name: nginx
        image: eu.gcr.io/brynn-145714/bolagetio/nginx:latest
        lifecycle:
          preStop:
            exec:
              command: ["sleep", "30"]
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /ready
            port: 80
          periodSeconds: 1
          successThreshold: 1
          failureThreshold: 1
        livenessProbe:
          httpGet:
            path: /ready
            port: 80
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 1
