apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: bolagetio
spec:
  revisionHistoryLimit: 2
  minReadySeconds: 5
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: eu.gcr.io/brynn-145714/bolagetio/elasticsearch:latest
        imagePullPolicy: Always
        env:
        - name: ES_HEAP_SIZE
          value: "512m"
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        resources:
          limits:
            memory: 1Gi
