apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web
  namespace: bolagetio
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: eu.gcr.io/brynn-145714/bolagetio/web:latest
        imagePullPolicy: Always
        env:
        - name: NODE_ENV
          value: "production"
        - name: ES_HOST
          value: "elasticsearch.bolagetio:9200"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: bolagetio
spec:
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: web
