apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
  namespace: bolagetio
spec:
  revisionHistoryLimit: 2
  minReadySeconds: 5
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: eu.gcr.io/brynn-145714/bolagetio/nginx:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 5
