apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: job
  namespace: bolagetio
spec:
  schedule: "00 03 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: job
            image: eu.gcr.io/brynn-145714/bolagetio/web-deployment:latest
            imagePullPolicy: Always
            envFrom:
            - configMapRef:
                name: web-config
            command: ["node", ".build/worker.js"]
          restartPolicy: OnFailure
