apiVersion: batch/v1
kind: Job
metadata:
  name: worker
  namespace: bolagetio
spec:
  template:
    metadata:
      name: worker
    spec:
      containers:
      - name: worker
        image: eu.gcr.io/brynn-145714/bolagetio/web:latest
        imagePullPolicy: Always
        env:
          - name: NODE_ENV
            valueFrom:
              configMapKeyRef:
                name: web-v1
                key: node_env
          - name: ES_HOST
            valueFrom:
              configMapKeyRef:
                name: web-v1
                key: es_host
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: web-v1
                key: port
        command: ["npm", "run", "worker"]
      restartPolicy: Never
