apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: es
  namespace: bolagetio
  labels:
    component: elasticsearch
spec:
  serviceName: es
  replicas: 3
  template:
    metadata:
      labels:
        component: elasticsearch
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: component
                  operator: In
                  values:
                  - elasticsearch
              topologyKey: kubernetes.io/hostname
      serviceAccount: elasticsearch
      initContainers:
      - name: init-sysctl
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      containers:
      - name: es
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
        image: quay.io/pires/docker-elasticsearch-kubernetes:6.1.2
        resources:
          requests:
            memory: "256Mi"
          limits:
            memory: "512Mi"
        env:
        - name: KUBERNETES_CA_CERTIFICATE_FILE
          value: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CLUSTER_NAME
          value: "es"
        - name: DISCOVERY_SERVICE
          value: "es"
        - name: NODE_MASTER
          value: "true"
        - name: NODE_DATA
          value: "true"
        - name: HTTP_ENABLE
          value: "true"
        - name: ES_PLUGINS_INSTALL
          value: "analysis-icu"
        - name: ES_JAVA_OPTS
          value: "-Xms256m -Xmx256m"
        - name: NUMBER_OF_MASTERS
          value: "2"
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: transport
          initialDelaySeconds: 20
          periodSeconds: 10
        volumeMounts:
        - mountPath: /data
          name: storage
  volumeClaimTemplates:
  - metadata:
      name: storage
    spec:
      storageClassName: ssd
      accessModes: [ ReadWriteOnce ]
      resources:
        requests:
          storage: 1Gi
