name: ci

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: docker-compose -f docker-compose.yaml -f docker-compose.test.yaml run web

  web:
    needs: test
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push web container
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: services/web
          file: ./services/web/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            fredriklack/bolagetio-web:${{github.sha}}
            fredriklack/bolagetio-web:latest
  elastic:
    needs: test
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push elastic container
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: services/elasticsearch
          file: ./services/elasticsearch/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            fredriklack/bolagetio-elastic:7.5.1
            fredriklack/bolagetio-elastic:latest
