apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: web
  namespace: bolagetio
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: web
  minReplicas: 4
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
