apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web
  namespace: bolagetio
spec:
  revisionHistoryLimit: 2
  replicas: 5
  minReadySeconds: 5
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
        web: bolagetio-web
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: web
                  operator: In
                  values:
                  - bolagetio-web
              topologyKey: kubernetes.io/hostname
      containers:
      - name: web
        image: eu.gcr.io/brynn-145714/bolagetio/web:latest
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: web-v2
        ports:
        - containerPort: 3000
        - containerPort: 3001
        readinessProbe:
          httpGet:
            path: /ready
            port: 3001
          periodSeconds: 1
          initialDelaySeconds: 5
          successThreshold: 1
          failureThreshold: 1
        livenessProbe:
          httpGet:
            path: /ready
            port: 3001
          periodSeconds: 10
          initialDelaySeconds: 10
          successThreshold: 1
          failureThreshold: 1
        lifecycle:
          preStop:
            httpGet:
              path: /prestop
              port: 3001
