apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web-deployment
  namespace: bolagetio
spec:
  revisionHistoryLimit: 2
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web-deployment
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - web-deployment
              topologyKey: kubernetes.io/hostname
      containers:
      - name: web
        image: eu.gcr.io/brynn-145714/bolagetio/web-deployment:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "200Mi"
        envFrom:
        - configMapRef:
            name: web-config
        ports:
        - containerPort: 3000
        - containerPort: 3001
        readinessProbe:
          httpGet:
            path: /ready
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 1
          successThreshold: 1
          failureThreshold: 1
        livenessProbe:
          httpGet:
            path: /ready
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 1
        lifecycle:
          preStop:
            httpGet:
              path: /prestop
              port: 3001
